### ISSUE TITLE
hey, wanna to join pypi?

### ISSUE THREAD

**Issue by wswuai** [someus/TextRank4ZH#2]
i think this project is very cool, 

this might to be a part of pypi (python package index)

if we submit this , the users can setup your package by "pip install textrank4zh"  

it's pretty cool, uh?

i'm willing to help to do that. 

are you interested to do it?

-------

and i think this preformance of this project can be improved ,too.

maybe i can be a participant of this project.

waiting for your reply, :)

**Comment by someus** [comment]
Recently I'm busy looking for a job and do not have enough time to maintain this project. Welcome you to join this project :)

**Comment by wswuai** [comment]
:)

okay , good luck!
