### ISSUE TITLE
请问textrank能否用于多文本的自动摘要？

### ISSUE THREAD

**Issue by cyh24** [someus/TextRank4ZH#3]
请问textrank能否用于多文本的自动摘要？

**Comment by someus** [comment]
请问什么是“多文本”？

**Comment by cyh24** [comment]
可能是我描述的不好，应该是多文档的自动摘要。也就是说从多个（内容相近的）文档中提取出摘要。

**Comment by someus** [comment]
目前是从一个文本中提取。你的问题可以有两种思路：  
1、每个文本提取一些，多个文本合并到一起。 
2、多个文本合并到一起，从这个大文本中提取。

就看效果满不满意了～～

**Comment by cyh24** [comment]
好的，我试试，多谢您的回答。
