### ISSUE TITLE
cannot create dir when installing networkx

### ISSUE THREAD

**Issue by jrong75** [someus/TextRank4ZH#6]
creating /System/Library/Frameworks/Python.framework/Versions/2.7/share
    error: could not create '/System/Library/Frameworks/Python.framework/Versions/2.7/share': Operation not permitted
    
    ----------------------------------------
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-Ol6WG2/networkx/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-8kdl8t-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-Ol6WG2/networkx

**Comment by someus** [comment]
应该是权限问题。我对mac不熟，使用Mac下的类似root的权限试一下。
